global_costmap:
    global_frame: map
    rolling_window: false
    track_unknown_space: true

    plugins:
        - {name: static,                  type: "costmap_2d::StaticLayer"}
        - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,               type: "costmap_2d::InflationLayer"}

    static:
      first_map_only: true

