global_costmap:
    global_frame: map
    rolling_window: false
    track_unknown_space: true

    plugins:
        - {name: localization_map, type: "costmap_2d::StaticLayer"}
        - {name: preferences_map, type: "costmap_2d::StaticLayer"}
        - {name: obstacles_costmap2d, type: "costmap_2d::ObstacleLayer"}
        - {name: demonstration, type: "demonstration_layer::DemonstrationLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    localization_map:
      map_topic: "/map"
      first_map_only: true

    preferences_map:
      map_topic: "/preferences_map"
      first_map_only: true

